---
subtitle: "Compléments 2.0"
cache: true
---



```{r}
#| label: info

rm(list=ls())
classeur <- "complement2.xlsx"
expx <- FALSE

library(corrplot)
library(baseph)
library(tidyverse)
library(kableExtra)
library(janitor)
library(gtsummary)
library(labelled)
library(DataExplorer)
library(WriteXLS)
library(colorspace)

# sessionInfo()
```


```{r}
#| label: import

bnom <- read.csv("datas/bnom.csv")
ttd <- read_delim("datas/drepa2.csv", delim = ",", show_col_types = FALSE) |> 
  clean_names() |> 
  mutate_if(is.character, as.factor)
var_label(ttd) <- bnom$nom
#
ttd$imcx <- bmiph(ttd$imc, "fr")
var_label(ttd$imcx) <- "IMC"
ttd <- ttd |> 
  relocate(imcx, .after = imc)
## Recodage de tt$cvo_an en tt$cvo_an_rec
ttd$cvo_an <- cut(ttd$cvo_an,
  include.lowest = TRUE,
  right = FALSE,
  dig.lab = 4,
  breaks = c(0, 1, 2, 3, 4,5, 10,50), 
  labels = c("0","1","2","3","4","5-10",">10")
)
var_label(ttd$cvo_an) <- "Nb de CVO hospitalisée par an en moyenne"
#
## Recodage de tt$sta en tt$sta_rec
# ttd$sta<- cut(ttd$sta,
#   include.lowest = TRUE,
#   right = FALSE,
#   dig.lab = 4,
#   breaks = c(0, 1, 2, 3,4,6, 11, 25),
#   labels = c("0","1","2","3","4-5","6-10",">10")
# )
#
befr <- read.csv("datas/befr.csv")
efr <- read_delim("datas/efr.csv",delim = ",") |> 
  clean_names()
var_label(efr) <- befr$nom
#
efr$tvo <- as.factor(ifelse(efr$vems_cvf_percent < (efr$vems_cvf_lin*100), "Oui","Non"))
efr$tvr <- as.factor(ifelse((efr$vems_l < efr$vems_lin_l) & (efr$cvf_l < efr$cvf_lin_l), "Oui","Non"))
efr$dlcob <- as.factor(ifelse((efr$dlc_ocor_percent < 70) & (efr$tvr == "Non") & (efr$tvo == "Non"), "Oui","Non" ))
var_label(efr$tvo) <- "TVO"
var_label(efr$tvr) <- "TVR"
var_label(efr$dlcob) <- "DLCOc basse isolée"

tt <- left_join(ttd,efr[,c(1,2,4,6,7,9,10,16:27)],"id")
#
bnom <- read.csv("datas/bgroupe.csv")
bnom <- bnom$nom
ttg <- debutph("datas/groupe.csv", bnom)
ttg <- left_join(ttg,tt,"id")
```

## Description de la population

```{r}
#| label: tabdesc
#| tbl-cap: Tableau descriptif - Groupes
tt |> 
  dplyr::select(2:8, sta,cvo_an) |>
  mutate('au moins un STA' = ifelse(sta > 0, "yes", "no")) |>
  mutate('au moins une CVO' = ifelse(cvo_an != "0", "yes", "no")) |>
tbl_summary(by = groupe,
            missing = "no",
            type = all_continuous() ~ "continuous2",
            statistic = all_continuous() ~ c(
      "{median} ({p25}, {p75})",
      "{mean}, {sd}",
      "{min}, {max}")) |> 
     
    add_overall() %>%
 modify_header(label ~ " ") |> 
   bold_labels() |> 
  add_n() |>
  add_p() |>
 pexptabph(exp = expx, nomfich = classeur, nomsheet = "demographie")
```



## Dyspnée

 
Tout dépend de la référence prise (in fine les deux calculs sont non contributifs).

### Patients dyspnéiques
La dyspnée est définie par un mMRC > 1 ou Borg post test > 3 (@tbl-ouid). 

```{r}
#| label: dyspnee1

ttg <- ttg |> 
  mutate(dysp = ifelse((m_mrc > 1 | borg_post > 3), "Dyspnée modérée à sévère", "Dyspnée faible ou absente")) |> 
  mutate(dysp = as.factor(dysp))
```

## Traitements

```{r}
#| label: tbl-traitements
#| tbl-cap: Traitements

tt |> 
 dplyr::select(24:29,groupe) |> 
 tbl_summary(by = groupe,
            missing = "no") |> 
    add_overall() %>%
 modify_header(label ~ " ") |> 
   bold_labels() |> 
  add_n() |>
  add_p() |>
 pexptabph(exp = expx, nomfich = classeur, nomsheet = "traitement")
```


## Dyspnée

```{r}
#| label: tbl-dyspnee2
#| tbl-cap: Dyspnée

tt <- tt |> 
 mutate(dyspnee = ifelse((m_mrc > 1 | borg_post > 3), "yes", "no")) 
 var_label(tt$dyspnee) <- "Dyspnée"

tt |> 
  dplyr::select(dyspnee, groupe) |> 
  tbl_summary(by = groupe,
              missing = "no") |> 
    add_overall() %>%
  modify_header(label ~ " ") |> 
   bold_labels() |> 
    add_n() |>
    add_p()|>
 pexptabph(exp = expx, nomfich = classeur, nomsheet = "dyspnee")
```


## Anomalies au scanner thoracique

```{r}
zz <- tt |> 
  select(47:102) |> 
  mutate_all(function(x) if_else(x == "yes",1,0))
  anomalie = rowSums(zz,na.rm = TRUE)
tt$anomalie <- anomalie


tt <- tt |> 
  mutate(anomalie = ifelse(anomalie > 0, "yes", "no"))
var_label(tt$anomalie) <- "Au moins une anomalie au scanner thoracique"
tt |> 
  dplyr::select(anomalie, groupe) |> 
  tbl_summary(by = groupe,
              missing = "no") |> 
    add_overall() %>%
  modify_header(label ~ " ") |> 
   bold_labels() |> 
    add_n() |>
    add_p()|>
 pexptabph(exp = expx, nomfich = classeur, nomsheet = "anomalie")
```
